### ISSUE TITLE
IndexError when processing a single hydrogen

### ISSUE THREAD

**Issue by ghiander** [AstraZeneca/jazzy#287]
**Describe the bug**
When a single hydrogen molecule is processed by the calculate_polar_strength_map() function, the code raises a IndexError because the neighbour list is zero for this molecule.

**To Reproduce**
```
Steps to reproduce the behavior:
>>> import jazzy
>>> from jazzy.api import deltag_from_smiles
>>> deltag_from_smiles("[H]")
[09:18:56] WARNING: not removing hydrogen atom without neighbors
[09:18:56] WARNING: not removing hydrogen atom without neighbors
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kdxr003/.local/lib/python3.8/site-packages/jazzy/api.py", line 113, in deltag_from_smiles
    atomic_map = calculate_polar_strength_map(
  File "/home/kdxr003/.local/lib/python3.8/site-packages/jazzy/core.py", line 231, in calculate_polar_strength_map
    if nbr[0].GetAtomicNum() == 6:
IndexError: tuple index out of range
```

**Expected behavior**
A single hydrogen cannot produce hydrogen bond, hence, there its strength can be assumed to be zero. Also, it does not make any sense to run this calculation on this compound. The code can be changed to have ```if nbr: do stuff```

**Screenshots**
Not needed.

**Additional context**

**Comment by ghiander** [comment]
https://github.com/AstraZeneca/jazzy/pull/326
